name: Update Markets

on:
  schedule:
    - cron: '51 4 * * *'
  workflow_dispatch:

jobs:
  update-markets:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up PowerShell
        uses: actions/setup-powershell@v2
      - name: Update Markets
        shell: pwsh
        run: ./Update-Markets-GHA.ps1
